Implement Fibonacci#each
zxftr45/kottans_2016_homeworks pull request #4
Opened 2016-11-04 22:21 UTC by brbrr

2016-11-12 21:26 UTC, denysxftr requested changes
plz check https://gitter.im/Kottans/Ruby2016-Kyiv?at=582782cf31c5cbef43ea360a

2016-11-12 21:26 UTC, zxftr45 commented on hw2/lib/router.rb
> +    return %r{^\/post\/[\w\d]+$} if path =~ %r{^\/post\/:.+$}
hardcoded to `post` in url

2016-11-13 10:54 UTC, brbrr commented on hw2/lib/router.rb
> +    return %r{^\/post\/[\w\d]+$} if path =~ %r{^\/post\/:.+$}
fixed in latest commit

2016-11-27 16:07 UTC, denysxftr approved these changes

2016-11-27 16:07 UTC, zxftr45 commented
nice

2025-01-19 03:51 UTC, closed without merging